[package]
name = "liquid-sql"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[features]
postgres-integration = []

[dependencies]
async-trait.workspace = true
pg_query.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true

[dev-dependencies]
criterion.workspace = true
tokio.workspace = true

[[bench]]
name = "postgres_static_analysis"
harness = false
