{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "liquid.postgresqlFullname" . }}
  labels:
    {{- include "liquid.componentLabels" (dict "root" . "component" "postgresql") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "liquid.selectorLabels" (dict "root" . "component" "postgresql") | nindent 4 }}
{{- end }}
