{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "liquid.postgresqlSecretName" . }}
  labels:
    {{- include "liquid.componentLabels" (dict "root" . "component" "postgresql") | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
