{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "liquid.frontendFullname" . }}
  labels:
    {{- include "liquid.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "liquid.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
{{- end }}
