[package]
name = "liquid-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "liquid"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
liquid-agent.workspace = true
liquid-api.workspace = true
liquid-config.workspace = true
liquid-llm.workspace = true
liquid-storage.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
