[package]
name = "liquid-api"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
axum.workspace = true
futures-util.workspace = true
liquid-agent.workspace = true
liquid-config.workspace = true
liquid-core.workspace = true
liquid-sql.workspace = true
liquid-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true

[dev-dependencies]
async-trait.workspace = true
serde_json.workspace = true
time.workspace = true
tower = { workspace = true, features = ["util"] }
