[package]
name = "liquid-agent"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
futures-core.workspace = true
futures-util.workspace = true
liquid-core = { path = "../liquid-core" }
liquid-llm = { path = "../liquid-llm" }
liquid-sql = { path = "../liquid-sql" }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true

[dev-dependencies]
tokio.workspace = true
