[package]
name = "liquid-agent"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
futures-core.workspace = true
futures-util.workspace = true
liquid-core.workspace = true
liquid-llm.workspace = true
liquid-sql.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
